name: Security Scans

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write   # pour uploader le SARIF de gitleaks

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare reports dir
        run: mkdir -p reports

      # --- GITLEAKS (via image Docker, pas de licence requise) ---
      - name: Run Gitleaks (docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/path" \
            zricethezav/gitleaks:latest \
            detect --source /path \
                   --report-format sarif \
                   --report-path /path/reports/gitleaks.sarif \
                   --redact \
          || true

      - name: Upload Gitleaks SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/gitleaks.sarif

      # --- Build image pour Trivy & Snyk ---
      - name: Build Docker image
        run: docker build -t devsecure-api:local .

      # --- TRIVY (scan image) ---
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.24.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2
        with:
          image-ref: devsecure-api:local
          format: json
          output: reports/trivy-image.json
          ignore-unfixed: true

      # --- SNYK CONTAINER (nécessite SNYK_TOKEN si tu en as un) ---
      - name: Run Snyk Container
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          docker run --rm \
            -e SNYK_TOKEN=${SNYK_TOKEN} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${{ github.workspace }}:/project" -w /project \
            snyk/snyk:docker \
            sh -c "snyk container test devsecure-api:local --file=/project/Dockerfile --json-file-output=/project/reports/snyk-container.json || true"

      # --- Upload des rapports JSON ---
      - name: Upload all reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/*
          if-no-files-found: warn
